name: Bug report
description: Report a reproducible problem
title: "[Bug] "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting this issue. Please provide enough detail so it can be reproduced.
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What is the bug?
      placeholder: Briefly describe the problem.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Exact steps from app start to failure
      placeholder: |
        1. Open ...
        2. Click ...
        3. See error ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: What should have happened?
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      placeholder: What happened instead?
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs or error output
      description: Paste terminal/browser/API errors if available
      render: shell
  - type: input
    id: os
    attributes:
      label: OS
      placeholder: e.g. Windows 11
    validations:
      required: true
  - type: input
    id: php
    attributes:
      label: PHP version
      placeholder: e.g. 8.4.17 (`php -v`)
    validations:
      required: true
  - type: input
    id: browser
    attributes:
      label: Browser
      placeholder: e.g. Chrome 122
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Drag and drop screenshots if relevant
