name: Feature request
description: Suggest an improvement or new capability
title: "[Feature] "
labels:
  - enhancement
body:
  - type: markdown
    attributes:
      value: |
        Thanks for the suggestion. Clear problem statements make prioritization easier.
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What problem does this solve?
      placeholder: Describe the user problem or friction.
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: What should be added or changed?
      placeholder: Describe expected behavior and UX.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Optional
      placeholder: Any alternative approaches?
  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - Onboarding / Plex auth
        - Roulette
        - Lists (Watchlist / Watched / Dismissed)
        - Watch Now
        - Battles
        - Profile / Settings
        - Documentation
        - Other
    validations:
      required: true
  - type: textarea
    id: impact
    attributes:
      label: Expected impact
      description: Who benefits and how?
      placeholder: e.g. faster setup, fewer clicks, better filtering
